pipeline:
  build:
    image: python:3.6
    commands:        
      - pip install -r requirements.txt pytest
      - python setup.py install
      - pytest

  pypi_publish:
    image: username502/drone-pypi:latest
    secrets: [ PYPI_REPOSITORY, PYPI_USERNAME, PYPI_PASSWORD ]
    when:
      branch: master
      event: tag
  
  codecov:
    image: username502/drone-codecov
    token: $${CODECOV_TOKEN}
    secrets: [CODECOV_TOKEN]

  notify:
    image: drillster/drone-email
    host: smtp.mailgun.org
    port: 25
    username: email_username
    password: email_password
    from: drone@mg.guser.ru
    recipients: [ skar404@gmail.com ]
    secrets: [ email_username, email_password ]
    when:
      status: [ changed, failure ]
