pipeline:
  build:
    image: python:3.6
    commands:        
      - pip install -r requirements.txt pytest pytest-cov codecov
      - python setup.py install
      - pytest
    secrets: [CODECOV_TOKEN]

  coverage:
    commands:
      - pip install -r requirements.txt pytest pytest-cov codecov
      - python setup.py install
      - pytest --cov=./
      - codecov -t $${CODECOV_TOKEN}
    secrets: [CODECOV_TOKEN]
    when:
      branch: master

  pypi_publish:
    image: username502/drone-pypi:latest
    secrets: [ PYPI_REPOSITORY, PYPI_USERNAME, PYPI_PASSWORD ]
    when:
      branch: master
      event: tag
